### 금융상품 갱신 여부 예측하는 ANN 

Churn_Modelling.csv 파일을 보면, 고객 정보와 해당 고객이 금융상품을 갱신했는지 안했는지의 여부에 대한 데이터가 있다.

이 데이터를 가지고 갱신여부를 예측하는 딥러닝을 구성하시오.

# Neural Networks and Deep Learning

In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
# Churn_Modelling.csv 파일을 읽어올것이다.
# 구글 드라이브를 연동해서 읽어온다.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
# 파이썬에서 디렉토리 경로 이동하는 방법

In [5]:
import os

In [6]:
os.chdir('/content/drive/MyDrive/Colab Notebooks/ml_plus/data')

In [7]:
df = pd.read_csv('Churn_Modelling.csv')

In [8]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [9]:
# nan 있는지 확인

In [10]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [11]:
#  X, y 로 분리

In [12]:
y = df['Exited']

In [13]:
df.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [14]:
X = df.loc[ : , 'CreditScore' :  'EstimatedSalary' ]

In [15]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [16]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [17]:
# 문자열 데이터는 숫자로 바꿔줘야 한다.

In [20]:
X['Geography'].nunique()

3

In [22]:
X['Gender'].nunique()

2

In [23]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [24]:
from sklearn.compose import ColumnTransformer

In [25]:
label_encoder = LabelEncoder()

In [27]:
X['Gender'] = label_encoder.fit_transform(X['Gender'])

In [28]:
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [29]:
ct = ColumnTransformer( [ ('encoder', OneHotEncoder(), [1]) ] ,
                       remainder='passthrough')

In [31]:
X = ct.fit_transform(X.values)

In [32]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
# dummy variable trap
#
# France, Germerny, Spain 3개 컬럼으로 만들었는데,
# 실제로는 원핫 인코딩을 수행한 후에, 맨 왼쪽 컬럼은 삭제해도
# 0 과 1로 데이터를 전부 나타낼 수 있다.

# 즉, France 컬럼을 삭제해도

#  Germerny , Spain  
#   0          0        => 프랑스
#   1          0        => 독일
#   0          1        => 스페인 

# 이렇게 맨 왼쪽 france 컬럼을 삭제해도, 3개의 데이터를 모두 나타낼수있다.


In [33]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [36]:
X_df = pd.DataFrame(X)

In [38]:
X_df.drop(0, axis =1 , inplace=True )

In [40]:
X = X_df.values

In [41]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [42]:
# 피처스케일링한다.

#####  딥러닝은 무조건 피처스케일링 해야 한다 ##########

In [43]:
from sklearn.preprocessing import MinMaxScaler

In [44]:
X

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [45]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [46]:
scaler_X = MinMaxScaler()

In [48]:
X = scaler_X.fit_transform(X)

In [49]:
# 학습용과 테스트용으로 데이터를 나눈다. 

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [52]:
X_train.shape

(8000, 11)

In [53]:
X_test.shape

(2000, 11)

In [54]:
y_train.shape

(8000,)

In [55]:
y_test.shape

(2000,)

In [57]:
X_train[ 0 , : ]

array([0.        , 1.        , 0.634     , 0.        , 0.21621622,
       0.5       , 0.        , 0.33333333, 1.        , 0.        ,
       0.81917353])

In [61]:
y_train.values[0]

0

In [62]:
# Part 2 - Now let's make the ANN!

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [82]:
model = Sequential()

In [83]:
model.add(  Dense(units = 6, activation='relu', input_shape= (11,)  )      )

In [84]:
model.add(  Dense(units = 8, activation= tf.nn.relu  )   )

In [85]:
model.add( Dense(units = 1, activation='sigmoid')  )

In [86]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 6)                 72        
                                                                 
 dense_4 (Dense)             (None, 8)                 56        
                                                                 
 dense_5 (Dense)             (None, 1)                 9         
                                                                 
Total params: 137
Trainable params: 137
Non-trainable params: 0
_________________________________________________________________


In [87]:
# 모델링이 끝나면, 컴파일(Compile)을 해야 한다. 
# 컴파일이란, 옵티마이저(optimizer)와 로스펑션(loss function 오차함수, 손실함수 ), 검증방법을 셋팅

In [88]:
# 2개로 분류하는 문제의 loss 는  'binary_crossentropy' 을 설정한다.
model.compile(optimizer='adam', loss='binary_crossentropy', metrics= [ 'accuracy' ] )

In [89]:
# 컴파일이 끝나면, 학습을 한다.

In [90]:
##### 주의점 : 학습 코드를 실행한후에, 다시 학습하고 싶을때는, 모델링 부분부터 다시 실행해야 합니다.

In [91]:
X_train.shape

(8000, 11)

In [92]:
model.fit(X_train, y_train, batch_size= 10, epochs= 20)

Epoch 1/20
800/800 [==============================] - 2s 2ms/step - loss: 0.5089 - accuracy: 0.7960
Epoch 2/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4554 - accuracy: 0.8019
Epoch 3/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4407 - accuracy: 0.8075
Epoch 4/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4347 - accuracy: 0.8089
Epoch 5/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4302 - accuracy: 0.8121
Epoch 6/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4263 - accuracy: 0.8127
Epoch 7/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4226 - accuracy: 0.8156
Epoch 8/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4195 - accuracy: 0.8170
Epoch 9/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4142 - accuracy: 0.8174
Epoch 10/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4104 - accuracy: 0.8194

In [81]:
8000 / 250

32.0

In [ ]:
# 학습이 끝나면, 평가를 한다. 

In [93]:
model.evaluate(X_test, y_test)

63/63 [==============================] - 0s 2ms/step - loss: 0.3856 - accuracy: 0.8405


[0.3856365978717804, 0.840499997138977]

In [94]:
# 컨퓨전 매트릭스를 확인하여, 어떤 문제를 잘 맞추고 못맞추는지 확인

In [95]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [97]:
y_pred = model.predict(X_test)

63/63 [==============================] - 0s 2ms/step


In [98]:
y_pred

array([[0.20196299],
       [0.29562798],
       [0.1781193 ],
       ...,
       [0.24332559],
       [0.15902865],
       [0.16173074]], dtype=float32)

In [102]:
y_pred = (y_pred > 0.5).astype(int)

In [103]:
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [99]:
y_test

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [105]:
cm = confusion_matrix(y_test, y_pred)

In [106]:
cm

array([[1515,   80],
       [ 239,  166]])

In [107]:
(1515+166) / cm.sum()

0.8405

In [108]:
accuracy_score(y_test, y_pred)

0.8405

In [109]:
model.layers[0].weights

[<tf.Variable 'dense_3/kernel:0' shape=(11, 6) dtype=float32, numpy=
 array([[-6.2538600e-01,  3.9553726e-01, -3.9352554e-01,  4.0074864e-01,
          2.1039166e-01, -1.5666054e-01],
        [ 6.8517514e-02,  9.3497939e-02,  2.1130380e-01,  2.6232982e-01,
         -1.9760224e-01, -2.0819534e-02],
        [ 2.5023565e-01,  3.0791318e-02,  3.4550452e-01, -4.1281938e-04,
          2.9508233e-01,  3.1108919e-01],
        [ 1.7890716e-02, -1.7565878e-01,  1.5888257e-01, -1.6902190e-01,
          6.3308515e-03,  4.5557328e-02],
        [ 4.1106799e-01,  1.1305641e+00, -4.7474620e-01, -1.2119011e+00,
         -7.0616376e-01,  4.9538080e-02],
        [-5.7843118e-03,  2.1327573e-01, -1.7458847e-01,  1.9133903e-01,
          2.4650702e-01,  4.8896533e-01],
        [-1.1918960e+00,  6.3924342e-01, -5.2024186e-01,  3.5554004e-01,
          1.6304100e-01, -1.3493301e-01],
        [-2.2522936e+00,  1.5678903e-01, -5.1310045e-01, -5.2320641e-02,
          2.0411678e-01, -3.3288088e-01],
        [ 2

In [111]:
X_train[0, :]

array([0.        , 1.        , 0.634     , 0.        , 0.21621622,
       0.5       , 0.        , 0.33333333, 1.        , 0.        ,
       0.81917353])

In [118]:
model.layers[1].weights

[<tf.Variable 'dense_4/kernel:0' shape=(6, 8) dtype=float32, numpy=
 array([[-1.1023608 , -0.3650461 , -0.76858616, -0.85142726,  0.8540209 ,
         -1.0720279 , -0.64344645, -0.48392576],
        [-0.18827853, -0.7171827 , -0.03803644, -0.8596618 ,  0.8564529 ,
         -1.109777  , -0.5957272 ,  0.10527419],
        [ 0.8241777 ,  0.0934754 , -0.42490953,  0.7706603 , -0.08763823,
          0.3654917 , -0.1314741 , -0.5017845 ],
        [-0.40608954,  0.5016727 ,  0.34486857,  0.66081434, -0.07557455,
          0.24668184,  0.27912444,  0.47321185],
        [-0.29807988,  0.6968363 , -0.50739634,  0.72023994,  0.42416275,
          0.7329658 ,  0.00146901, -0.5583984 ],
        [ 0.3739425 , -0.2760431 ,  0.69670916, -0.3208409 , -0.1341379 ,
          0.3971774 ,  0.5288231 ,  0.51600343]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(8,) dtype=float32, numpy=
 array([0.4134472 , 0.3306209 , 0.32376432, 0.41827196, 0.09148301,
        0.3313296 , 0.47446564, 0.28941318],

## 다음 신규 데이터를 통해 분류해 보자

- Geography: France
- Credit Score: 600
- Gender: Male
- Age: 40
- Tenure: 3
- Balance: 60000
- Number of Products: 2
- Has Credit Card: Yes
- Is Active Member: Yes
- Estimated Salary: 50000

In [119]:
df.head(2)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   

   Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2      0.00              1          1               1   
1       1  83807.86              1          0               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0

In [120]:
new_data = np.array( [ 600, 'France', 'Male', 40, 3, 60000,  2, 1 , 1 , 50000 ] )

In [125]:
new_data.shape

(10,)

In [126]:
X_test.shape

(2000, 11)

In [128]:
new_data = new_data.reshape(1, 10 )

In [129]:
new_data

array([['600', 'France', 'Male', '40', '3', '60000', '2', '1', '1',
        '50000']], dtype='<U21')

In [130]:
new_data[ : , 2 ]

array(['Male'], dtype='<U21')

In [132]:
new_data[ : , 2 ] = label_encoder.transform(  new_data[ : , 2 ]  )

In [133]:
new_data

array([['600', 'France', '1', '40', '3', '60000', '2', '1', '1', '50000']],
      dtype='<U21')

In [135]:
new_data = ct.transform( new_data )

In [136]:
new_data

array([['1.0', '0.0', '0.0', '600', '1', '40', '3', '60000', '2', '1',
        '1', '50000']], dtype='<U32')

In [138]:
new_data = new_data[  : ,  1 :   ]

In [139]:
new_data

array([['0.0', '0.0', '600', '1', '40', '3', '60000', '2', '1', '1',
        '50000']], dtype='<U32')

In [141]:
new_data = scaler_X.transform(new_data)

In [143]:
y_pred = model.predict(new_data)

1/1 [==============================] - 0s 18ms/step


In [144]:
y_pred

array([[0.08781379]], dtype=float32)

In [146]:
(y_pred > 0.5).astype(int)

array([[0]])

In [148]:
label_encoder

LabelEncoder()

In [149]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [1])])

In [150]:
scaler_X

MinMaxScaler()

In [151]:
model

### 용어 정리

epoch

- 한 번의 epoch는 신경망에서 전체 데이터 셋에 대해 forward pass/backward pass 과정을 거친 것을 말함. 즉, 전체 데이터 셋에 대해 한 번 학습을 완료한 상태


batch_size

메모리의 한계와 속도 저하 때문에 대부분의 경우에는 한 번의 epoch에서 모든 데이터를 한꺼번에 집어넣을 수는 없습니다. 그래서 데이터를 나누어서 주게 되는데 이때 몇 번 나누어서 주는가를 iteration, 각 iteration마다 주는 데이터 사이즈를 batch size라고 합니다.

출처: https://www.slideshare.net/w0ong/ss-82372826

### GridSearch 를 이용한, 최적의 하이퍼 파라미터 찾기

In [ ]:
# Tuning the ANN
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
